# Введение

SQL - это особенный язык программирования. С его помощью мы не напишем полноценное приложение или сайт. Это язык структурированных запросов и используют его для работы с базами данных(БД).

Сущность -это тип объекта реального мира, который требуется хранить в программе (Товар, продавец)

Атрибут - это свойство сущности, характерное для всех или большинства экземпляров сущности (для товара: цена, артикул; для продавца: сайт, адрес)

Связь - это некоторая логическая связь между объектами реального мира (У товара есть продавец. Продавцу принадлежат различные товары)

Ограничения, характерные для предметной области (Количество цифр в номере телефона фиксировано, цена не может быть отрицательной, название товара не может быть пустым, все артикулы должны быть уникальными и так далее)

Реляционная база данных – это набор данных с предопределенными связями(отношениями) между ними. В реляционной БД данные представляются в виде плоской таблицы.

Столбцы таблиц в различных источниках могут называться следующим образом:
Columns
Поля
Fields
Атрибуты

Строки могут встречаться, как записи, кортежи, records или rows

Каждая строка таблицы представляет собой набор связанных значений, относящихся к одному объекту или сущности. Каждая строка в таблице может быть помечена уникальным идентификатором, называемым Первичным Ключом (Primary Key), а строки из нескольких таблиц могут быть связаны с помощью Внешних Ключей (Foreign key). 

Для того чтобы столбец мог быть первичным ключом в реляционной базе данных, он должен содержать уникальные значения и не иметь NULL. 

Например, таблица Товары связана с таблицей Поставщики внешним ключом по полям: Товары.Поставщик(указан идентификатор) - Поставщик.Идентификатор.

Реляционная модель БД наиболее эффективно поддерживает целостность данных во всех приложениях и копиях базы данных.

СУБД - система управления базами данных — посредник между пользователем и сервером, где находятся таблицы; это комплекс программно-языковых средств, позволяющих создать базы данных и управлять данными. 

Наиболее популярные СУБД - MySQL (скорость, гибкость, бесплатно), Oracle (дорогоб объектно-реляционная), Microsoft SQL Server (Windows, Linux, дорого), PostgreSQL (бесплатно, объктно-реляционная)

# Символьные и бинарные типы данных

В столбцах с типом CHAR могут храниться строки Фиксированной (одинаковой) длины, которая дополняется Пробелами до значения <количество символов>. Тип CHAR может хранить до 255 байт.

В столбцах с типом VARCHAR могут храниться строки Переменной длины, отличающиеся от типа CHAR тем, что НЕ дополняется пробелами до максимальной длины. Максимальный размер до 65535 байт.

Типы данных BINARY и VARBINARY аналогичны CHAR и VARCHAR , только они хранят двоичные строки. Тип BINARY  с фиксированной длиной, строки дополняются нулевым байтом до максимальной длины. VARBINARY хранит строки переменной длины, поэтому дополняться нулевыми байтами не будет.

BLOB (TINYBLOB, BLOB, MEDIUMBLOB и LONGBLOB) используется для хранения больших бинарных данных, таких как картинки. TEXT (TINYTEXT, TEXT, MEDIUMTEXT и LONGTEXT) предназначен также для хранения больших данных, но текстового содержания.

ENUM строковый объект со значением, выбранным из списка разрешенных значений, которые перечислены явно в спецификации столбца при создании таблицы.

SET строковый объект, у которого может быть ноль или больше значений, каждое из которых должно быть выбрано из списка разрешенных значений, определенных, когда таблица составлена.

# Числовые типы данных

MySQL поддерживает следующие категории типов данных: типы с фиксированной точкой (DECIMAL; NUMERIC, DEC, FIXED), типы с плавающей точкой (FLOAT), целочисленные типы (INT), тип битового значения (BIT)

DECIMAL имеет точность (общее кол-во разрядов; по умолчанию 10, max 65) и масштаб (кол-во разрядов справа от точки; по умолч-ю =0)

FLOAT тоже имеет (общее кол-во цифр, кол-во цифр после запятой), а также хранит дробные числа с плавающей точкой одинарной точности от  −3.4028 ∗ 10^38 до 3.4028 ∗ 10^38, занимает 4 байта

DOUBLE (REAL, DOUBLE PRECISION) отличается от FLOAT только тем, что хранит дробные числа с плавающей точкой двойной точности от -1.7976 * 10^308 до 1.7976 * 10^308, занимает 8 байт.

INT имеет типы TINYINT, SMALLINT, MEDIUMINT, INT и BIGINT

BIT - <количество бит> - может принимать значения от 1 до 64, по умолчанию - 8 бит. Если назначаемое значение в колонке с данным типом использует меньше M бит, то происходит дополнение нулями слева.

# Дата и время

Типы данных: DATE (YYYY-MM-DD), DATETIME = TIMESTAMP, TIME, YEAR

DATETIME - Этот тип данных не зависит от временной зоны, установленной в MySQL. Он всегда отображается ровно в таком виде, в котором был установлен и в котором хранится в базе данных. То есть при изменении часового пояса, отображение времени не изменится.

TIMESTAMP отличается от предыдущего тем, что при выборках отображается с учётом текущего часового пояса

дату, время, год можно записывать строкой/числом

MySQL конвертирует недопустимые значения YEAR в 0000.

# Создание таблиц

Синтаксис команды для создания таблицы в MySQL выглядит следующим образом: 

CREATE TABLE название_таблицы(

название_столбца1 тип_данных1 атрибуты_столбца1,

название_столбца2 тип_данных2 атрибуты_столбца2,

…

название_столбцаN тип_данныхN атрибуты_столбцаN,

атрибуты_таблицы
);

Если нужно создать таблицу с данными из других таблиц, например, Создать счет (таблицу buy_pay) на оплату заказа с номером 5, в который включить название книг, их автора, цену, количество заказанных книг и  стоимость. Последний столбец назвать Стоимость.

CREATE TABLE buy_pay AS

SELECT book.title, author.name_author, book.price, buy_book.amount, (book.price*buy_book.amount) AS Стоимость FROM buy_book

INNER JOIN book USING (book_id) INNER JOIN author USING (author_id)

WHERE buy_id = 5;

# Правила целостности

MySQL позволяет задавать условия, которым должны удовлетворять данные в базе. Программист задает условие, а сервер обеспечивает проверку при любом изменении данных. Такие условия называются правилами целостности.

Правила целостности MySQL:

1. Запрет неопределенных значений (not null)
2. Уникальность значения (unique)
3. Первичный ключ (Primary key)

Кроме того, для ограничения ссылочной целостности существуют внешние ключи (foreign key).

NULL - это специальное значение, которое используется в SQL для обозначения отсутствия какого-либо значения в ячейке таблицы.  (! не равно 0).

NOT NULL - проверка на непустое значение.

Выставим столбцу full_name ограничение на пустое значение - после типа данных пропишем NOT NULL:

CREATE TABLE patients
(   
    full_name VARCHAR(100) NOT NULL,

    sex CHAR(1),

    birth_date DATE,

    oms_num BIGINT
);

Если таблица уже создана пользуемся ALTER:

ALTER TABLE patients CHANGE full_name full_name VARCHAR(100) NOT NULL;

 Теперь, если мы решим вставить новую строку в таблицу patients с незаполненным full_name, то СУБД выдаст нам ошибку - поле full_name не может содержать NULL значение.

Согласно правилу UNIQUE, в таблице не может существовать двух строк с одинаковыми значениями столбца или набора столбцов.

NULL'ы могут быть UNIQUE

На практике указывается так:

CREATE TABLE patients
(   
    full_name VARCHAR(100) NOT NULL,

    sex CHAR(1),

    birth_date DATE,

    oms_num BIGINT UNIQUE
);
Добавить к уже существующей так же, как с NOT NULL

Первичный ключ — поле или комбинация полей в таблице, которое позволяет однозначно идентифицировать каждую запись в ней. Значение в столбце считается первичным ключом, если оно непустое (NOT NULL) и уникально в пределах столбца данной таблицы (UNIQUE). Первичный ключ может быть составным и представлять собой комбинацию столбцов.

Создать первичный ключ можно двумя способами: 

1. CREATE TABLE med_area
(
    area_num TINYINT,
    area_address VARCHAR(1000) ,
    PRIMARY KEY (area_num)
);

2. CREATE TABLE med_area
(
    area_num TINYINT PRIMARY KEY,
    area_address VARCHAR(1000)
); # этот способ сработает, если первичный ключ это ОДИН столбец

Чтобы добавить первичный ключ к существующей таблице:

ALTER TABLE med_area ADD PRIMARY KEY(area_num);

ДОБАВЛЕНИЕ СТОЛБЦА

ALTER TABLE patients
ADD COLUMN card_num(название) INT(тип);

Внешний ключ - это поле или набор полей, перечисленных через запятую, количество и типы данных которых совпадают с количеством и типом данных полей первичного ключа в родительской таблице.

Синтаксис определения внешнего ключа (применимый только в рамках создания таблицы):

CREATE TABLE название_таблицы(
<блок описания полей>

,FOREIGN KEY (название_поля) REFERENCES название_родительской_таблицы(название_поля_родит_таблицы)
);

Создание внешнего ключа при создании дочерней таблицы (на примере таблицы Пациентов):

CREATE TABLE patients
(
    full_name VARCHAR(100) NOT NULL,

    sex CHAR(1),

    birth_date DATE,
    
    oms_num BIGINT UNIQUE,
    
    card_num INT,
    
    area_num TINYINT, 
    
    FOREIGN KEY (area_num) REFERENCES med_area(area_num)
);

При добавлении в уже существующую таблицу: 

ALTER TABLE patients ADD FOREIGN KEY (area_num) REFERENCES med_area(area_num);

! Обратите внимание, что тип данных поля area_num в родительской и дочерней таблице должны совпадать!

# Еще про таблицы

AUTO_INCREMENT -это атрибут столбца. Указывает, что значение данной колонки будет автоматически увеличиваться при добавлении новых записей в таблицу. Каждая таблица имеет максимум одну AUTO_INCREMENT колонку. Стоит отметить, что данный параметр можно применять только к целочисленным типам и к типам с плавающей запятой. Последовательности AUTO_INCREMENT начинаются с 1, с шагом 1.

Синтаксис при создании таблицы: 
CREATE TABLE med_area
(
    area_num TINYINT AUTO_INCREMENT,
    area_address VARCHAR(1000),
    PRIMARY KEY (area_num)
);

И если уже существует:
ALTER TABLE med_area CHANGE area_num area_num TINYINT AUTO_INCREMENT;

DEFAULT - Указывает значение по умолчанию. Если при вставке строки значение для столбца с указанным DEFAULT не будет задано, то в него запишется значение по умолчанию.

CREATE TABLE patients
(
    full_name VARCHAR(100) NOT NULL,
    sex CHAR(1) DEFAULT 'м',
    birth_date DATE,
    oms_num BIGINT UNIQUE,
    card_num INT,
    area_num TINYINT, 
    FOREIGN KEY (area_num) REFERENCES med_area(area_num)
);

Если уже есть:
ALTER TABLE patients CHANGE sex sex CHAR(1) DEFAULT 'м';

Чтобы посмотреть описание созданной таблицы:
DESCRIBE med_area;

Чтобы удалить таблицу:
DROP TABLE [IF EXISTS] имя_таблицы;
Параметр в [] указан для того, чтобы избежать аварийной остановки программы в случае отсутствия такой таблицы